[package]
name = "mydbms"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.68"                               
bytes = "1.3.0"                                 
thiserror = "1.0.38"                            
regex= "1.12.2"